name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up SSH Agent to SSH into EC2 using the private key stored in GitHub secrets
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      # Build the Docker image for the FastAPI backend
      - name: Build Docker Image
        run: |
          docker build -t fastapi-backend .

      # SSH into EC2 and deploy the Docker container
      - name: Deploy Docker Container on EC2
        env:
          EC2_IP: ${{ secrets.EC2_PUBLIC_IP }}  # Using GitHub secret for EC2 public IP
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@$EC2_IP << EOF
            # Pull the latest Docker image
            docker pull fastapi-backend || { echo 'Docker pull failed'; exit 1; }

            # Stop any running container of the same name
            docker stop fastapi-backend || true

            # Remove any stopped container
            docker rm fastapi-backend || true

            # Run the new Docker container
            docker run -d -p 8000:8000 --name fastapi-backend fastapi-backend || { echo 'Docker run failed'; exit 1; }

            echo "Deployment Successful"
          EOF
